name: Build Containers for Staging & Push to Dockerhub

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-deploy-docker-image:
    name: Build docker image and push
    runs-on: ubuntu-latest
    #if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Build dev image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            lsj2767/my-react-demo
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # pull-docker-image:
  #   needs: build-and-deploy-docker-image
  #   name: "Pull docker image"
  #   runs-on: ubuntu-latest
  #   # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  #   # needs: test
  #   steps:
  #     - name: pull docker image
  #       uses: caprover/deploy-from-github@main
  #       with:
  #         server: '${{ secrets.CAPROVER_SERVER }}'
  #         app: '${{ secrets.APP_NAME }}'
  #         token: '${{ secrets.APP_TOKEN }}'
  #         image: '${{ secrets.DEPLOY_IMAGE }}' # optional
  pull-docker-image:
    needs: build-and-deploy-docker-image
    name: 'Pull docker image'
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: test
    #if: github.event_name == 'push'
    steps:
      - name: pull docker image
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.STAGING_SSH_HOST }}
          username: root
          password: ${{ secrets.STAGING_SSH_PASSWORD}}
          script: |
            echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull lsj2767/my-react-demo

  start-project:
    needs: pull-docker-image
    name: 'Start project'
    runs-on: ubuntu-latest
    #if: github.event_name == 'push'
    steps:
      - name: start project
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.STAGING_SSH_HOST }}
          username: root
          password: ${{ secrets.STAGING_SSH_PASSWORD}}
          script: |
            cd /home/my-react-demo/
            docker-compose down
            # sleep 3
            # docker-compose up -d
            # sleep 5
            # cd /home/my-react-demo/blue
            # docker-compose down
            # sleep 3
            docker-compose up -d
